### ISSUE TITLE
:Tree -split=floating does not work

### ISSUE THREAD

**Issue by uaisu** [zgpio/travis#20]
![image](https://user-images.githubusercontent.com/102277445/165733529-37484990-8de0-4b58-b060-ed31cbc240e2.png)

我觉得这个插件挺有意思的，但是已经不维护了吗？

**Comment by zgpio** [comment]
输入参数不对，比方说没有设置要显示的列，因为没有做参数检查，就异常退出了

**Comment by zgpio** [comment]
我复现不了，先关了，等有复现步骤再打开
