### ISSUE TITLE
How to build/install/use?

### ISSUE THREAD

**Issue by kutsan** [zgpio/travis#3]

**Comment by zgpio** [comment]
Currently, it is recommended to download the [release](https://github.com/zgpio/tree.nvim/releases) and use it.
It contains the complete neovim plugin structure and the tree.nvim executable.
```
├── autoload
├── bin
├── doc
├── lua
└── plugin
```
Soon, I will support mainstream plugin manager such as `dein`, `plug`, etc.
~~Note that currently tree.nvim does not yet support `copy/move/paste` action.~~

**Comment by kutsan** [comment]
Thanks man. Great work by the way, it looks really promising.

**Comment by r-glebov** [comment]
Hey guys, sorry, I don't really get how to install it on mac. Manual in Readme doesn't help much, at least for me. Much appreciate your help!
