### ISSUE TITLE
If renaming to another directory, the redrawing is not accurate

### ISSUE THREAD

**Issue by litao91** [zgpio/travis#4]
For example, 

If we rename from `/tmp/a/b` to `/tmp/b`, the tree's buffer won't change. 

We either need to redraw the current tree and the target tree or simply redraw the entire tree.

**Comment by zgpio** [comment]
Thanks for your use and feedback, temporary fix in c34c1665fdf51f123cdf789c85e857cf4f059598: refresh the tree buffer directly.
